/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UsageEntry = IDL.Record({
  'id' : IDL.Nat,
  'staffName' : IDL.Text,
  'staffId' : IDL.Nat,
  'clientName' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'time' : IDL.Text,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'category' : IDL.Text,
});
export const Staff = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
});
export const DailyReport = IDL.Record({
  'date' : IDL.Text,
  'grandTotal' : IDL.Nat,
  'staffGroups' : IDL.Vec(
    IDL.Record({
      'staffName' : IDL.Text,
      'entries' : IDL.Vec(UsageEntry),
      'totalQuantity' : IDL.Nat,
    })
  ),
});
export const MonthlyReport = IDL.Record({
  'month' : IDL.Text,
  'staffTotals' : IDL.Vec(
    IDL.Record({
      'staffName' : IDL.Text,
      'entryCount' : IDL.Nat,
      'totalQuantity' : IDL.Nat,
    })
  ),
  'year' : IDL.Text,
  'productTotals' : IDL.Vec(
    IDL.Record({
      'productName' : IDL.Text,
      'category' : IDL.Text,
      'totalQuantity' : IDL.Nat,
    })
  ),
});

export const idlService = IDL.Service({
  'addEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [UsageEntry],
      [],
    ),
  'addProduct' : IDL.Func([IDL.Text, IDL.Text], [Product], []),
  'addStaff' : IDL.Func([IDL.Text], [Staff], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteStaff' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getDailyReport' : IDL.Func([IDL.Text], [DailyReport], ['query']),
  'getEntries' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'entries' : IDL.Vec(UsageEntry) })],
      ['query'],
    ),
  'getEntriesFiltered' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Record({ 'total' : IDL.Nat, 'entries' : IDL.Vec(UsageEntry) })],
      ['query'],
    ),
  'getMonthlyReport' : IDL.Func(
      [IDL.Text, IDL.Text],
      [MonthlyReport],
      ['query'],
    ),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Opt(Product)],
      [],
    ),
  'updateStaff' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Staff)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UsageEntry = IDL.Record({
    'id' : IDL.Nat,
    'staffName' : IDL.Text,
    'staffId' : IDL.Nat,
    'clientName' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'time' : IDL.Text,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'category' : IDL.Text,
  });
  const Staff = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
  });
  const DailyReport = IDL.Record({
    'date' : IDL.Text,
    'grandTotal' : IDL.Nat,
    'staffGroups' : IDL.Vec(
      IDL.Record({
        'staffName' : IDL.Text,
        'entries' : IDL.Vec(UsageEntry),
        'totalQuantity' : IDL.Nat,
      })
    ),
  });
  const MonthlyReport = IDL.Record({
    'month' : IDL.Text,
    'staffTotals' : IDL.Vec(
      IDL.Record({
        'staffName' : IDL.Text,
        'entryCount' : IDL.Nat,
        'totalQuantity' : IDL.Nat,
      })
    ),
    'year' : IDL.Text,
    'productTotals' : IDL.Vec(
      IDL.Record({
        'productName' : IDL.Text,
        'category' : IDL.Text,
        'totalQuantity' : IDL.Nat,
      })
    ),
  });
  
  return IDL.Service({
    'addEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [UsageEntry],
        [],
      ),
    'addProduct' : IDL.Func([IDL.Text, IDL.Text], [Product], []),
    'addStaff' : IDL.Func([IDL.Text], [Staff], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteStaff' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getDailyReport' : IDL.Func([IDL.Text], [DailyReport], ['query']),
    'getEntries' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'entries' : IDL.Vec(UsageEntry) })],
        ['query'],
      ),
    'getEntriesFiltered' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Record({ 'total' : IDL.Nat, 'entries' : IDL.Vec(UsageEntry) })],
        ['query'],
      ),
    'getMonthlyReport' : IDL.Func(
        [IDL.Text, IDL.Text],
        [MonthlyReport],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Opt(Product)],
        [],
      ),
    'updateStaff' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Staff)], []),
  });
};

export const init = ({ IDL }) => { return []; };