/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyReport {
  'date' : string,
  'grandTotal' : bigint,
  'staffGroups' : Array<
    {
      'staffName' : string,
      'entries' : Array<UsageEntry>,
      'totalQuantity' : bigint,
    }
  >,
}
export interface MonthlyReport {
  'month' : string,
  'staffTotals' : Array<
    { 'staffName' : string, 'entryCount' : bigint, 'totalQuantity' : bigint }
  >,
  'year' : string,
  'productTotals' : Array<
    { 'productName' : string, 'category' : string, 'totalQuantity' : bigint }
  >,
}
export interface Product {
  'id' : bigint,
  'active' : boolean,
  'name' : string,
  'category' : string,
}
export interface Staff { 'id' : bigint, 'active' : boolean, 'name' : string }
export interface UsageEntry {
  'id' : bigint,
  'staffName' : string,
  'staffId' : bigint,
  'clientName' : [] | [string],
  'date' : string,
  'time' : string,
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
}
export interface _SERVICE {
  'addEntry' : ActorMethod<
    [string, bigint, string, bigint, string, bigint, string, [] | [string]],
    UsageEntry
  >,
  'addProduct' : ActorMethod<[string, string], Product>,
  'addStaff' : ActorMethod<[string], Staff>,
  'deleteEntry' : ActorMethod<[bigint], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'deleteStaff' : ActorMethod<[bigint], boolean>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllStaff' : ActorMethod<[], Array<Staff>>,
  'getDailyReport' : ActorMethod<[string], DailyReport>,
  'getEntries' : ActorMethod<
    [bigint, bigint],
    { 'total' : bigint, 'entries' : Array<UsageEntry> }
  >,
  'getEntriesFiltered' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      bigint,
      bigint,
    ],
    { 'total' : bigint, 'entries' : Array<UsageEntry> }
  >,
  'getMonthlyReport' : ActorMethod<[string, string], MonthlyReport>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getStaff' : ActorMethod<[], Array<Staff>>,
  'updateProduct' : ActorMethod<[bigint, string, string], [] | [Product]>,
  'updateStaff' : ActorMethod<[bigint, string], [] | [Staff]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];