/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MonthlyReport {
    month: string;
    staffTotals: Array<{
        staffName: string;
        entryCount: bigint;
        totalQuantity: bigint;
    }>;
    year: string;
    productTotals: Array<{
        productName: string;
        category: string;
        totalQuantity: bigint;
    }>;
}
export interface DailyReport {
    date: string;
    grandTotal: bigint;
    staffGroups: Array<{
        staffName: string;
        entries: Array<UsageEntry>;
        totalQuantity: bigint;
    }>;
}
export interface UsageEntry {
    id: bigint;
    staffName: string;
    staffId: bigint;
    clientName?: string;
    date: string;
    time: string;
    productId: bigint;
    productName: string;
    quantity: bigint;
}
export interface Product {
    id: bigint;
    active: boolean;
    name: string;
    category: string;
}
export interface Staff {
    id: bigint;
    active: boolean;
    name: string;
}
export interface backendInterface {
    addEntry(date: string, productId: bigint, productName: string, staffId: bigint, staffName: string, quantity: bigint, time: string, clientName: string | null): Promise<UsageEntry>;
    addProduct(name: string, category: string): Promise<Product>;
    addStaff(name: string): Promise<Staff>;
    deleteEntry(id: bigint): Promise<boolean>;
    deleteProduct(id: bigint): Promise<boolean>;
    deleteStaff(id: bigint): Promise<boolean>;
    getAllProducts(): Promise<Array<Product>>;
    getAllStaff(): Promise<Array<Staff>>;
    getDailyReport(_date: string): Promise<DailyReport>;
    getEntries(page: bigint, pageSize: bigint): Promise<{
        total: bigint;
        entries: Array<UsageEntry>;
    }>;
    getEntriesFiltered(productName: string | null, staffName: string | null, fromDate: string | null, toDate: string | null, page: bigint, pageSize: bigint): Promise<{
        total: bigint;
        entries: Array<UsageEntry>;
    }>;
    getMonthlyReport(_month: string, _year: string): Promise<MonthlyReport>;
    getProducts(): Promise<Array<Product>>;
    getStaff(): Promise<Array<Staff>>;
    updateProduct(id: bigint, name: string, category: string): Promise<Product | null>;
    updateStaff(id: bigint, name: string): Promise<Staff | null>;
}
import type { DailyReport as _DailyReport, Product as _Product, Staff as _Staff, UsageEntry as _UsageEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEntry(arg0: string, arg1: bigint, arg2: string, arg3: bigint, arg4: string, arg5: bigint, arg6: string, arg7: string | null): Promise<UsageEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
                return from_candid_UsageEntry_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
            return from_candid_UsageEntry_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addProduct(arg0: string, arg1: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1);
            return result;
        }
    }
    async addStaff(arg0: string): Promise<Staff> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaff(arg0);
            return result;
        }
    }
    async deleteEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEntry(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteStaff(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaff(arg0);
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getAllStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff();
            return result;
        }
    }
    async getDailyReport(arg0: string): Promise<DailyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyReport(arg0);
                return from_candid_DailyReport_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyReport(arg0);
            return from_candid_DailyReport_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntries(arg0: bigint, arg1: bigint): Promise<{
        total: bigint;
        entries: Array<UsageEntry>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntries(arg0, arg1);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntries(arg0, arg1);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntriesFiltered(arg0: string | null, arg1: string | null, arg2: string | null, arg3: string | null, arg4: bigint, arg5: bigint): Promise<{
        total: bigint;
        entries: Array<UsageEntry>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesFiltered(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesFiltered(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyReport(arg0: string, arg1: string): Promise<MonthlyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyReport(arg0, arg1);
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaff();
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStaff(arg0: bigint, arg1: string): Promise<Staff | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaff(arg0, arg1);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaff(arg0, arg1);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DailyReport_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyReport): DailyReport {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UsageEntry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UsageEntry): UsageEntry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Staff]): Staff | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    entries: Array<_UsageEntry>;
}): {
    total: bigint;
    entries: Array<UsageEntry>;
} {
    return {
        total: value.total,
        entries: from_candid_vec_n9(_uploadFile, _downloadFile, value.entries)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    staffName: string;
    staffId: bigint;
    clientName: [] | [string];
    date: string;
    time: string;
    productId: bigint;
    productName: string;
    quantity: bigint;
}): {
    id: bigint;
    staffName: string;
    staffId: bigint;
    clientName?: string;
    date: string;
    time: string;
    productId: bigint;
    productName: string;
    quantity: bigint;
} {
    return {
        id: value.id,
        staffName: value.staffName,
        staffId: value.staffId,
        clientName: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.clientName)),
        date: value.date,
        time: value.time,
        productId: value.productId,
        productName: value.productName,
        quantity: value.quantity
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    grandTotal: bigint;
    staffGroups: Array<{
        staffName: string;
        entries: Array<_UsageEntry>;
        totalQuantity: bigint;
    }>;
}): {
    date: string;
    grandTotal: bigint;
    staffGroups: Array<{
        staffName: string;
        entries: Array<UsageEntry>;
        totalQuantity: bigint;
    }>;
} {
    return {
        date: value.date,
        grandTotal: value.grandTotal,
        staffGroups: from_candid_vec_n7(_uploadFile, _downloadFile, value.staffGroups)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    staffName: string;
    entries: Array<_UsageEntry>;
    totalQuantity: bigint;
}): {
    staffName: string;
    entries: Array<UsageEntry>;
    totalQuantity: bigint;
} {
    return {
        staffName: value.staffName,
        entries: from_candid_vec_n9(_uploadFile, _downloadFile, value.entries),
        totalQuantity: value.totalQuantity
    };
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    staffName: string;
    entries: Array<_UsageEntry>;
    totalQuantity: bigint;
}>): Array<{
    staffName: string;
    entries: Array<UsageEntry>;
    totalQuantity: bigint;
}> {
    return value.map((x)=>from_candid_record_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UsageEntry>): Array<UsageEntry> {
    return value.map((x)=>from_candid_UsageEntry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
